export const chatListData = [
      {id: 1, avatar: "https://source.unsplash.com/random/50x50", name: "hello", onlineStatus: "online", lastSeen: new Date(), lastSeen: new Date()},
      {id: 2, avatar: "https://source.unsplash.com/random/50x50", name: "how", onlineStatus: "online", lastSeen: new Date()},
      {id: 3, avatar: "https://source.unsplash.com/random/50x50", name: "stephen", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 23, 13, 30, 0)},
      {id: 4, avatar: "https://source.unsplash.com/random/50x50", name: "hawking", onlineStatus: "online", lastSeen: new Date()},
      {id: 5, avatar: "https://source.unsplash.com/random/50x50", name: "robert", onlineStatus: "online", lastSeen: new Date()},
      {id: 6, avatar: "https://source.unsplash.com/random/50x50", name: "einstein", onlineStatus: "online", lastSeen: new Date()},
      {id: 7, avatar: "https://source.unsplash.com/random/50x50", name: "nasa", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 11, 33, 30, 0)},
      {id: 8, avatar: "https://source.unsplash.com/random/50x50", name: "ISRO", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 11, 39, 30, 0)},
      {id: 9, avatar: "https://source.unsplash.com/random/50x50", name: "space", onlineStatus: "online", lastSeen: new Date()},
      {id: 10, avatar: "https://source.unsplash.com/random/50x50", name: "react", onlineStatus: "offline", lastSeen: new Date(2018, 6, 24, 6, 33, 30, 0)},
      {id: 11, avatar: "https://source.unsplash.com/random/50x50", name: "native", onlineStatus: "online", lastSeen: new Date()},
      {id: 12, avatar: "https://source.unsplash.com/random/50x50", name: "angular", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 1, 33, 30, 0)},
      {id: 13, avatar: "https://source.unsplash.com/random/50x50", name: "html", onlineStatus: "online", lastSeen: new Date()},
      {id: 14, avatar: "https://source.unsplash.com/random/50x50", name: "css", onlineStatus: "online", lastSeen: new Date()},
      {id: 15, avatar: "https://source.unsplash.com/random/50x50", name: "javascript", onlineStatus: "online", lastSeen: new Date()},
      {id: 16, avatar: "https://source.unsplash.com/random/50x50", name: "vue", onlineStatus: "offline", lastSeen: new Date(2018, 6, 24, 10, 33, 30, 0)},
      {id: 17, avatar: "https://source.unsplash.com/random/50x50", name: "redux", onlineStatus: "online", lastSeen: new Date()},
      {id: 18, avatar: "https://source.unsplash.com/random/50x50", name: "web", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 5, 45, 30, 0)},
      {id: 19, avatar: "https://source.unsplash.com/random/50x50", name: "development", onlineStatus: "online", lastSeen: new Date()},
      {id: 20, avatar: "https://source.unsplash.com/random/50x50", name: "codebrahma", onlineStatus: "online", lastSeen: new Date()},
      {id: 21, avatar: "https://source.unsplash.com/random/50x50", name: "cb", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 19, 10, 30, 0)},
      {id: 22, avatar: "https://source.unsplash.com/random/50x50", name: "some other", onlineStatus: "online", lastSeen: new Date()},
      {id: 23, avatar: "https://source.unsplash.com/random/50x50", name: "why not", onlineStatus: "online", lastSeen: new Date()},
      {id: 24, avatar: "https://source.unsplash.com/random/50x50", name: "sure", onlineStatus: "offline", lastSeen: new Date(2018, 6, 24, 9, 10, 30, 0)},
      {id: 25, avatar: "https://source.unsplash.com/random/50x50", name: "by default", onlineStatus: "online", lastSeen: new Date()},
      {id: 26, avatar: "https://source.unsplash.com/random/50x50", name: "dummy", onlineStatus: "online", lastSeen: new Date()},
      {id: 27, avatar: "https://source.unsplash.com/random/50x50", name: "data", onlineStatus: "online", lastSeen: new Date()},
      {id: 28, avatar: "https://source.unsplash.com/random/50x50", name: "wow", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 8, 20, 30, 0)},
      {id: 29, avatar: "https://source.unsplash.com/random/50x50", name: "i love WD", onlineStatus: "online", lastSeen: new Date()},
      {id: 30, avatar: "https://source.unsplash.com/random/50x50", name: "hurrah", onlineStatus: "online", lastSeen: new Date()},
      {id: 31, avatar: "https://source.unsplash.com/random/50x50", name: "are you", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 14, 50, 30, 0)},
      {id: 32, avatar: "https://source.unsplash.com/random/50x50", name: "who else", onlineStatus: "offline", lastSeen: new Date(2018, 6, 24, 10, 10, 30, 0)},
      {id: 33, avatar: "https://source.unsplash.com/random/50x50", name: "finally", onlineStatus: "offline", lastSeen: new Date(2018, 6, 23, 20, 33, 30, 0)},
      {id: 34, avatar: "https://source.unsplash.com/random/50x50", name: "last name", onlineStatus: "online", lastSeen: new Date()},
  ]
