export const userData = [{
    id: 1,
    avatar: require("./images/user-1.jpeg"),
    name: "hello",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet.",
  },
  {
    id: 2,
    avatar: require("./images/user-2.jpeg"),
    name: "how",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 3,
    avatar: require("./images/user-3.jpeg"),
    name: "stephen",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 23, 13, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 4,
    avatar: require("./images/user-4.jpeg"),
    name: "hawking",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Consectetur adipiscing elit.",
  },
  {
    id: 5,
    avatar: require("./images/user-5.jpeg"),
    name: "robert",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 6,
    avatar: require("./images/user-6.jpeg"),
    name: "einstein",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum amet, consectetur adipiscing elit.",
  },
  {
    id: 7,
    avatar: require("./images/user-7.jpeg"),
    name: "nasa",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 11, 33, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 8,
    avatar: require("./images/user-8.jpeg"),
    name: "ISRO",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 11, 39, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 9,
    avatar: require("./images/user-9.jpeg"),
    name: "space",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 10,
    avatar: require("./images/user-10.jpeg"),
    name: "react",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 24, 6, 33, 30, 0),
    previewMessage: "Lorem sit amet, consectetur adipiscing elit.",
  },
  {
    id: 11,
    avatar: require("./images/user-11.jpeg"),
    name: "native",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 12,
    avatar: require("./images/user-12.jpeg"),
    name: "angular",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 1, 33, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 13,
    avatar: require("./images/user-13.jpeg"),
    name: "html",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 14,
    avatar: require("./images/user-14.jpeg"),
    name: "css",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet elit.",
  },
  {
    id: 15,
    avatar: require("./images/user-15.jpeg"),
    name: "javascript",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, adipiscing elit.",
  },
  {
    id: 16,
    avatar: require("./images/user-16.jpeg"),
    name: "vue",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 24, 10, 33, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 17,
    avatar: require("./images/user-17.jpeg"),
    name: "redux",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 18,
    avatar: require("./images/user-1.jpeg"),
    name: "web",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 5, 45, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 19,
    avatar: require("./images/user-2.jpeg"),
    name: "development",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum, consectetur adipiscing elit.",
  },
  {
    id: 20,
    avatar: require("./images/user-3.jpeg"),
    name: "codebrahma",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 21,
    avatar: require("./images/user-4.jpeg"),
    name: "cb",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 19, 10, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 22,
    avatar: require("./images/user-5.jpeg"),
    name: "some other",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 23,
    avatar: require("./images/user-6.jpeg"),
    name: "why not",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 24,
    avatar: require("./images/user-7.jpeg"),
    name: "sure",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 24, 9, 10, 30, 0),
    previewMessage: "Adipiscing elit.",
  },
  {
    id: 25,
    avatar: require("./images/user-8.jpeg"),
    name: "by default",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 26,
    avatar: require("./images/user-9.jpeg"),
    name: "dummy",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 27,
    avatar: require("./images/user-10.jpeg"),
    name: "data",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur.",
  },
  {
    id: 28,
    avatar: require("./images/user-11.jpeg"),
    name: "wow",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 8, 20, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 29,
    avatar: require("./images/user-12.jpeg"),
    name: "i love WD",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 30,
    avatar: require("./images/user-13.jpeg"),
    name: "hurrah",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 31,
    avatar: require("./images/user-14.jpeg"),
    name: "are you",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 14, 50, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 32,
    avatar: require("./images/user-15.jpeg"),
    name: "who else",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 24, 10, 10, 30, 0),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 33,
    avatar: require("./images/user-16.jpeg"),
    name: "finally",
    onlineStatus: "offline",
    lastSeen: new Date(2018, 6, 23, 20, 33, 30, 0),
    previewMessage: "Amet, consectetur adipiscing elit.",
  },
  {
    id: 34,
    avatar: require("./images/user-17.jpeg"),
    name: "last name",
    onlineStatus: "online",
    lastSeen: new Date(),
    previewMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
]
