export const chatListData = [
      {id: 1, avatar: "https://source.unsplash.com/random/50x50", name: "hello", status: "active"},
      {id: 2, avatar: "https://source.unsplash.com/random/50x50", name: "how", status: "active"},
      {id: 3, avatar: "https://source.unsplash.com/random/50x50", name: "stephen", status: "inactive"},
      {id: 4, avatar: "https://source.unsplash.com/random/50x50", name: "hawking", status: "active"},
      {id: 5, avatar: "https://source.unsplash.com/random/50x50", name: "robert", status: "active"},
      {id: 6, avatar: "https://source.unsplash.com/random/50x50", name: "einstein", status: "active"},
      {id: 7, avatar: "https://source.unsplash.com/random/50x50", name: "nasa", status: "inactive"},
      {id: 8, avatar: "https://source.unsplash.com/random/50x50", name: "ISRO", status: "inactive"},
      {id: 9, avatar: "https://source.unsplash.com/random/50x50", name: "space", status: "active"},
      {id: 10, avatar: "https://source.unsplash.com/random/50x50", name: "react", status: "inactive"},
      {id: 11, avatar: "https://source.unsplash.com/random/50x50", name: "native", status: "active"},
      {id: 12, avatar: "https://source.unsplash.com/random/50x50", name: "angular", status: "inactive"},
      {id: 13, avatar: "https://source.unsplash.com/random/50x50", name: "html", status: "active"},
      {id: 14, avatar: "https://source.unsplash.com/random/50x50", name: "css", status: "active"},
      {id: 15, avatar: "https://source.unsplash.com/random/50x50", name: "javascript", status: "active"},
      {id: 16, avatar: "https://source.unsplash.com/random/50x50", name: "vue", status: "inactive"},
      {id: 17, avatar: "https://source.unsplash.com/random/50x50", name: "redux", status: "active"},
      {id: 18, avatar: "https://source.unsplash.com/random/50x50", name: "web", status: "inactive"},
      {id: 19, avatar: "https://source.unsplash.com/random/50x50", name: "development", status: "active"},
      {id: 20, avatar: "https://source.unsplash.com/random/50x50", name: "codebrahma", status: "active"},
      {id: 21, avatar: "https://source.unsplash.com/random/50x50", name: "cb", status: "inactive"},
      {id: 22, avatar: "https://source.unsplash.com/random/50x50", name: "some other", status: "active"},
      {id: 23, avatar: "https://source.unsplash.com/random/50x50", name: "why not", status: "active"},
      {id: 24, avatar: "https://source.unsplash.com/random/50x50", name: "sure", status: "inactive"},
      {id: 25, avatar: "https://source.unsplash.com/random/50x50", name: "by default", status: "active"},
      {id: 26, avatar: "https://source.unsplash.com/random/50x50", name: "dummy", status: "active"},
      {id: 27, avatar: "https://source.unsplash.com/random/50x50", name: "data", status: "active"},
      {id: 28, avatar: "https://source.unsplash.com/random/50x50", name: "wow", status: "inactive"},
      {id: 29, avatar: "https://source.unsplash.com/random/50x50", name: "i love WD", status: "active"},
      {id: 30, avatar: "https://source.unsplash.com/random/50x50", name: "hurrah", status: "active"},
      {id: 31, avatar: "https://source.unsplash.com/random/50x50", name: "are you", status: "active"},
      {id: 32, avatar: "https://source.unsplash.com/random/50x50", name: "who else", status: "inactive"},
      {id: 33, avatar: "https://source.unsplash.com/random/50x50", name: "finally", status: "inactive"},
      {id: 34, avatar: "https://source.unsplash.com/random/50x50", name: "last name", status: "active"},
  ]
